services:
  server:
    build:
      context: ./backend
      target: final
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  db:
    image: postgres:14.1-alpine
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "user"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=classroom
      - POSTGRES_PASSWORD=pwd
    ports:
      - '5434:5432'
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local