name: golangci-lint
on:
  push:
    branches:
      - main
      - master
      - staging
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.1  # Set Go version to 1.23.1
      - name: Cache Go modules (fresh cache each run)
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
      - name: Download dependencies
        run: go mod download
        working-directory: backend
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: backend
          version: v1.60
