name: Database Migration

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/kho-237/workflow-db-migration
    paths:
      - 'backend/database/migrations/001_khouryclassroom.sql'
      - '.github/workflows/db_migration.yml'

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    
    permissions:
        contents: read
        id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264409130:role/github-actions-deploy-role
          aws-region: us-east-2

      - name: Store Snapshot of AWS RDS Instance
        run: |
          aws rds create-db-snapshot --db-instance-identifier khouryclassroomdb --db-snapshot-identifier gitmarks-db-snapshot

      - name: Invoke AWS Lambda function
        uses: gagoar/invoke-aws-lambda@v3.4.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: us-east-2
          FunctionName: drop_db
          InvocationType: Event
          Payload: '{}'
