name: Database Migration

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/kho-237/workflow-db-migration
    paths:
      - 'backend/database/migrations/001_khouryclassroom.sql'
      - '.github/workflows/db_migration.yml'

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    
    permissions:
        contents: read
        id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264409130:role/github-actions-deploy-role
          aws-region: us-east-2

      - name: Store Snapshot of AWS RDS Instance
        run: |
          aws rds create-db-snapshot --db-instance-identifier gitmarks-rds-instance --db-snapshot-identifier gitmarks-db-snapshot

      - name: Invoke Lambda Function
        run: |
          aws lambda invoke \
            --function-name drop_db \
            --invocation-type Event \
            --cli-binary-format raw-in-base64-out \
            /dev/null
